version: '3'
services:
  db:
      container_name: db
      image: postgres:latest
      env_file:
        - .env
      environment:
          POSTGRES_USER: $DB_USER
          POSTGRES_PASSWORD: $DB_PASSWORD
          POSTGRES_DB: $DB_NAME
      networks:
        - app
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $DB_USER"]
        interval: 10s
        timeout: 5s
        retries: 5
  backend:
    container_name: backend
    build:
      context: Backend
      dockerfile: Dockerfile
    image: backend
    networks:
      - app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  #  frontend:
  #    container_name: frontend
  #    build:
  #      context: Frontend
  #      dockerfile: Dockerfile
  #    image: frontend
  #    networks:
  #      - app
  #    depends_on:
  #      - backend
  #    ports:
  #      - "4452:80"

networks:
  app:
    driver: bridge